// AUTO-GENERATED FROM signal-catalog.md — DO NOT EDIT.
// Edit the .md and run `bun run signals:gen` to regenerate.

import type { CapabilityKey } from "@/server/db/schema";
import type {
  ImportanceToRevenue,
  RunFrequency,
  SignalSpec,
} from "./signal-catalog";

export const SIGNAL_CATALOG: SignalSpec[] = [
  {
    capabilityKey: "seo_rank",
    name: "SEO Rank",
    description: "Current SERP position for the brand on tracked keywords.",
    category: "seo",
    source: "DataForSEO /v3/serp/google/organic/live/advanced",
    costPerCallUsd: 0.0006,
    costNote: "1 DataForSEO SERP task",
    groupedWith: ["seo_sov", "seo_traffic_trend", "seo_top_pages", "seo_answer_box", "seo_serp_features", "seo_keyword_changes"],
    dependsOn: [],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_keyword_gap",
    name: "Keyword Gap",
    description: "Keywords competitors rank for that the brand does not.",
    category: "seo",
    source: "DataForSEO /v3/keyword_gap",
    costPerCallUsd: 0.0006,
    costNote: "1 DataForSEO task",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_keyword_changes",
    name: "Keyword Portfolio Changes",
    description: "Gains/losses in keyword rankings day-over-day across the brand's portfolio.",
    category: "seo",
    source: "DataForSEO /v3/serp (delta vs prior signal_snapshot)",
    costPerCallUsd: 0,
    costNote: "Reuses SERP fetch + DB delta",
    groupedWith: ["seo_rank"],
    dependsOn: ["seo_rank"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_keyword_intent",
    name: "Keyword Intent",
    description: "Classifies tracked keywords by intent (transactional, informational, navigational).",
    category: "seo",
    source: "DataForSEO /v3/keyword_intent",
    costPerCallUsd: 0.0006,
    costNote: "1 DataForSEO task",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "monthly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_serp_features",
    name: "SERP Feature Ownership",
    description: "Counts featured snippets, knowledge panels, image packs the brand owns.",
    category: "seo",
    source: "Reuses seo_rank SERP fetch (feature_flags parsing)",
    costPerCallUsd: 0,
    costNote: "Reuses SERP payload",
    groupedWith: ["seo_rank"],
    dependsOn: ["seo_rank"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_sov",
    name: "Share of Voice",
    description: "Relative SERP visibility share vs competitors across the keyword universe.",
    category: "seo",
    source: "Reuses seo_rank SERP fetch (aggregate across keywords)",
    costPerCallUsd: 0,
    costNote: "Reuses SERP payload",
    groupedWith: ["seo_rank"],
    dependsOn: ["seo_rank"],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_traffic_trend",
    name: "Traffic Trend",
    description: "Estimated organic traffic WoW/MoM trend for the brand domain.",
    category: "seo",
    source: "DataForSEO /v3/dataforseo_labs/google/historical_serps",
    costPerCallUsd: 0.0006,
    costNote: "1 DataForSEO task",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_top_pages",
    name: "Competitor Top Pages",
    description: "Competitor's highest-traffic pages in organic search.",
    category: "seo",
    source: "DataForSEO /v3/dataforseo_labs/google/relevant_pages",
    costPerCallUsd: 0.0006,
    costNote: "1 DataForSEO task per competitor",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_backlinks",
    name: "Backlinks",
    description: "Domain authority + backlink count + referring domain count for the brand.",
    category: "seo",
    source: "DataForSEO /v3/backlinks/summary",
    costPerCallUsd: 0.0006,
    costNote: "1 DataForSEO task",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_cwv",
    name: "Core Web Vitals",
    description: "Google PageSpeed Insights: LCP, FID/INP, CLS lab and field data.",
    category: "seo",
    source: "Google PageSpeed Insights API + Chrome UX Report",
    costPerCallUsd: 0,
    costNote: "Free Google API (rate-limited)",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_content_score",
    name: "Content Score",
    description: "On-page content quality + SEO optimization score for the brand's top pages.",
    category: "seo",
    source: "DataForSEO /v3/content_analysis/summary",
    costPerCallUsd: 0.0006,
    costNote: "1 DataForSEO task",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_content_freshness",
    name: "Content Freshness",
    description: "Age of brand's top-ranking pages — days since last meaningful update.",
    category: "seo",
    source: "Firecrawl /v1/scrape (last-modified extraction)",
    costPerCallUsd: 0.005,
    costNote: "~5 Firecrawl scrapes for top pages",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_competitor_pages",
    name: "Competitor New Pages",
    description: "New content URLs published by competitors since last snapshot.",
    category: "seo",
    source: "Firecrawl /v1/map (delta vs prior signal_snapshot)",
    costPerCallUsd: 0.005,
    costNote: "1 Firecrawl map per competitor",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_sitemap_diff",
    name: "Sitemap Changes",
    description: "Own-site URL structure diff vs prior snapshot — new sections, removed pages, depth shifts.",
    category: "seo",
    source: "Firecrawl /v1/map (delta vs prior signal_snapshot)",
    costPerCallUsd: 0.005,
    costNote: "1 Firecrawl map call",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_index_coverage",
    name: "Index Coverage",
    description: "Deindex / index-coverage detection for the org's money pages, using GSC impressions as a coverage proxy.",
    category: "seo",
    source: "Composio GSC Search Analytics (page impressions)",
    costPerCallUsd: 0,
    costNote: "zero marginal cost via connected GSC account",
    groupedWith: ["seo_noindex_alert", "seo_canonical_drift"],
    dependsOn: ["seo_noindex_alert"],
    runFrequency: "daily" as RunFrequency,
    cached: false,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_noindex_alert",
    name: "Accidental Noindex",
    description: "Detects money pages that started returning noindex (a bad deploy can silently drop pages from search).",
    category: "seo",
    source: "Direct HTTP fetch of money pages (meta robots / X-Robots-Tag)",
    costPerCallUsd: 0,
    costNote: "plain HTTP fetch, no vendor cost",
    groupedWith: ["seo_canonical_drift"],
    dependsOn: ["seo_canonical_drift"],
    runFrequency: "daily" as RunFrequency,
    cached: false,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_canonical_drift",
    name: "Canonical Drift",
    description: "Detects money pages whose canonical URL changed or points off-page, which can deindex the page.",
    category: "seo",
    source: "Direct HTTP fetch of money pages (canonical link / header)",
    costPerCallUsd: 0,
    costNote: "plain HTTP fetch, no vendor cost",
    groupedWith: ["seo_noindex_alert"],
    dependsOn: ["seo_noindex_alert"],
    runFrequency: "daily" as RunFrequency,
    cached: false,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_content_decay",
    name: "Content Decay",
    description: "Own-site pages losing traffic vs the prior snapshot (>20% drop). Uses GSC clicks when connected, else DataForSEO per-page estimated organic traffic.",
    category: "seo",
    source: "Composio GSC clicks; DataForSEO ranked_keywords (per-page) fallback",
    costPerCallUsd: 0.01,
    costNote: "0 with GSC; 1 DataForSEO ranked_keywords call when GSC absent",
    groupedWith: ["seo_ctr_anomaly", "seo_index_coverage"],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_ctr_anomaly",
    name: "CTR Anomaly",
    description: "Own-site pages whose click-through rate fell sharply while impressions held steady (title/meta/SERP-appeal problem, not a ranking loss). GSC-only.",
    category: "seo",
    source: "Composio GSC Search Analytics (page impressions + clicks → CTR)",
    costPerCallUsd: 0,
    costNote: "zero marginal cost via connected GSC account; no-ops without GSC",
    groupedWith: ["seo_content_decay", "seo_index_coverage"],
    dependsOn: ["seo_content_decay"],
    runFrequency: "weekly" as RunFrequency,
    cached: false,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_error_spike",
    name: "404 / Redirect Errors",
    description: "Broken (4xx/5xx) and redirecting (3xx) URLs across the primary site's own discoverable URLs, with spike detection vs the prior snapshot.",
    category: "seo",
    source: "Firecrawl /v1/map inventory + HEAD status probes",
    costPerCallUsd: 0.005,
    costNote: "1 Firecrawl map call; HEAD probes are free",
    groupedWith: ["seo_sitemap_diff"],
    dependsOn: ["seo_sitemap_diff"],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_internal_linking",
    name: "Internal Linking Gaps",
    description: "Crawls the primary site, builds an inbound-link graph, and flags orphan pages (no internal links) and under-linked money pages.",
    category: "seo",
    source: "Firecrawl /v1/crawl (per-page links graph)",
    costPerCallUsd: 0.04,
    costNote: "~40 Firecrawl crawl page-credits",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "biweekly" as RunFrequency,
    cached: false,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_answer_box",
    name: "SERP Answer Box Ownership",
    description: "Share of branded queries where the brand owns the answer box / featured snippet.",
    category: "seo",
    source: "Reuses seo_rank SERP fetch (answer_box parsing)",
    costPerCallUsd: 0,
    costNote: "Reuses SERP payload",
    groupedWith: ["seo_rank"],
    dependsOn: ["seo_rank"],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_local_rank",
    name: "Local SEO Rank",
    description: "Position in Google Local Pack for local-intent keywords.",
    category: "seo",
    source: "DataForSEO /v3/serp/google/maps + /v3/serp/google/local",
    costPerCallUsd: 0.0012,
    costNote: "2 DataForSEO tasks",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_international_rank",
    name: "International SERP Rankings",
    description: "Average SERP rank across multiple country locales for the same keywords.",
    category: "seo",
    source: "DataForSEO /v3/serp/google/organic (per-locale fan-out)",
    costPerCallUsd: 0.003,
    costNote: "~5 SERP tasks (one per locale)",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_citations",
    name: "AI Citations",
    description: "Citation frequency of the brand's domain in answers from Claude, GPT, Gemini, Perplexity.",
    category: "geo",
    source: "OpenRouter (Claude Sonnet + others via OR routing)",
    costPerCallUsd: 0.02,
    costNote: "Multi-engine LLM probe; ~2k–4k tokens total",
    groupedWith: ["geo_mentions", "geo_engine_citations", "geo_keyword_citations", "geo_citation_sources", "geo_co_citations", "geo_citation_velocity"],
    dependsOn: [],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_mentions",
    name: "AI Brand Mentions",
    description: "Rate at which AI answers mention the brand by name (not just cite its domain).",
    category: "geo",
    source: "Reuses geo_citations probe responses",
    costPerCallUsd: 0,
    costNote: "Parses geo_citations responses",
    groupedWith: ["geo_citations"],
    dependsOn: ["geo_citations"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_mentions_geo",
    name: "AI Mentions by Country",
    description: "Geographic distribution of AI mentions across locale-tagged probes.",
    category: "geo",
    source: "OpenRouter (Claude Sonnet) — per-locale probes",
    costPerCallUsd: 0.04,
    costNote: "~5 locale-tagged probes",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_engine_citations",
    name: "Per-Engine Citations",
    description: "Citation breakdown by engine (OpenAI vs Anthropic vs Google vs Perplexity).",
    category: "geo",
    source: "Reuses geo_citations probe (per-engine grouping)",
    costPerCallUsd: 0,
    costNote: "Parses geo_citations responses",
    groupedWith: ["geo_citations"],
    dependsOn: [],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_keyword_citations",
    name: "Keyword Citation Matrix",
    description: "Citation rate keyed by each tracked keyword × each engine.",
    category: "geo",
    source: "Reuses geo_citations probe (keyword × engine pivot)",
    costPerCallUsd: 0,
    costNote: "Parses geo_citations responses",
    groupedWith: ["geo_citations"],
    dependsOn: ["geo_citations"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_citation_sources",
    name: "Citation Source Patterns",
    description: "Which third-party domains AI engines cite alongside the brand.",
    category: "geo",
    source: "Reuses geo_citations probe (cited-URL extraction)",
    costPerCallUsd: 0,
    costNote: "Parses geo_citations responses",
    groupedWith: ["geo_citations"],
    dependsOn: ["geo_citations"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_citation_velocity",
    name: "Citation Velocity",
    description: "Week-over-week percent change in citation count.",
    category: "geo",
    source: "DB analysis over historical signal_snapshots",
    costPerCallUsd: 0,
    costNote: "Pure DB analysis",
    groupedWith: ["geo_citations"],
    dependsOn: ["geo_citations"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_citation_authority",
    name: "Citation Authority",
    description: "Authority-weighted citation score (cites from high-DR domains count more).",
    category: "geo",
    source: "geo_citations sources + DataForSEO /v3/backlinks (cited-domain DR)",
    costPerCallUsd: 0.005,
    costNote: "Reuses geo_citations + small DataForSEO lookup",
    groupedWith: [],
    dependsOn: ["geo_citations"],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_citation_why",
    name: "Citation Causality",
    description: "Why the brand is cited — context, framing, sentiment around each mention.",
    category: "geo",
    source: "Reuses geo_citations probe + OpenRouter (Sonnet classification)",
    costPerCallUsd: 0.01,
    costNote: "Small LLM classification pass",
    groupedWith: [],
    dependsOn: ["geo_citations"],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_co_citations",
    name: "Co-Citations",
    description: "Brands cited together with this brand in AI answers (reveals AI's perceived peer set).",
    category: "geo",
    source: "Reuses geo_citations probe (brand-entity extraction)",
    costPerCallUsd: 0,
    costNote: "Parses geo_citations responses",
    groupedWith: ["geo_citations"],
    dependsOn: ["geo_citations"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_accuracy_audit",
    name: "AI Accuracy Audit",
    description: "Fact-checks AI claims about the brand against a ground-truth corpus.",
    category: "geo",
    source: "OpenRouter (Claude Sonnet) + ground-truth comparison",
    costPerCallUsd: 0.03,
    costNote: "LLM judge pass per claim",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_traffic_estimate",
    name: "AI Traffic Estimate",
    description: "Estimated monthly clicks from AI-generated citations to the brand's domain.",
    category: "geo",
    source: "Composite — citation rate × estimated AI query volume",
    costPerCallUsd: 0,
    costNote: "Pure DB analysis over signal_snapshots",
    groupedWith: [],
    dependsOn: ["geo_citations"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_traffic_lift",
    name: "AI Traffic Lift Projection",
    description: "Projected additional monthly AI-search clicks from realistic GEO optimizations (position lift, coverage, competitor parity).",
    category: "geo",
    source: "Derived — projection over geo_traffic_estimate citation positions",
    costPerCallUsd: 0,
    costNote: "Reuses same-day geo_traffic_estimate snapshot; re-probes only if absent",
    groupedWith: ["geo_traffic_estimate"],
    dependsOn: ["geo_traffic_estimate", "geo_competitor_visibility", "geo_content_gap"],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_competitor_visibility",
    name: "Competitor AI Visibility",
    description: "Brand's citation share vs each tracked competitor's citation share.",
    category: "geo",
    source: "OpenRouter (Claude Sonnet) — brand + competitor probes",
    costPerCallUsd: 0.04,
    costNote: "Probe per competitor",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_visibility_score",
    name: "GEO Visibility Score",
    description: "Composite 0–100 AI visibility score blending citations, mentions, accuracy, share.",
    category: "geo",
    source: "DB analysis over other geo_* signals",
    costPerCallUsd: 0,
    costNote: "Pure DB composite",
    groupedWith: [],
    dependsOn: ["geo_citations", "geo_mentions"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_alternatives",
    name: "Brand Alternatives",
    description: "How often competitors are suggested as alternatives to the brand by AI.",
    category: "geo",
    source: "OpenRouter (Claude Sonnet) — alternative-prompt probe",
    costPerCallUsd: 0.02,
    costNote: "Single multi-engine prompt",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_content_gap",
    name: "GEO Content Gap",
    description: "Topics competitors are cited for in AI answers that the brand has no content on.",
    category: "geo",
    source: "OpenRouter (Claude Sonnet) — gap-analysis prompt",
    costPerCallUsd: 0.02,
    costNote: "Single LLM pass",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_social_signals",
    name: "Social AI Signals",
    description: "Estimates how social-media presence is influencing AI training-data citations.",
    category: "geo",
    source: "OpenRouter (Claude Sonnet) + social-volume signals",
    costPerCallUsd: 0.02,
    costNote: "Single LLM pass",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_prompt_research",
    name: "AI Prompt Research",
    description: "Suggests prompts likely to surface (or hide) the brand in AI answers.",
    category: "geo",
    source: "OpenRouter (Claude Sonnet) — generative pass",
    costPerCallUsd: 0.02,
    costNote: "Single LLM pass",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_youtube_citations",
    name: "YouTube AI Citations",
    description: "How often YouTube videos about the brand appear in AI-generated answers.",
    category: "geo",
    source: "OpenRouter (Claude Sonnet) + YouTube Data API enrichment",
    costPerCallUsd: 0.02,
    costNote: "LLM probe + free YouTube API",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_shopping_citation",
    name: "Shopping Citations",
    description: "AEO/GEO shopping visibility: is the brand cited/recommended on buying-intent prompts (best/top/alternatives/vs), and who wins those answers instead.",
    category: "geo",
    source: "OpenRouter (Perplexity Sonar) — name-aware buying-intent recommendation probe",
    costPerCallUsd: 0.02,
    costNote: "buying-intent prompts × 2 Perplexity models",
    groupedWith: ["geo_keyword_citations", "geo_citations"],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_sentiment",
    name: "AI Sentiment Score",
    description: "Net sentiment of how AI answers describe the brand, rescaled to 0-100.",
    category: "geo",
    source: "Reuses geo_mentions probe responses",
    costPerCallUsd: 0,
    costNote: "Aggregates the same-day geo_mentions snapshot",
    groupedWith: ["geo_mentions"],
    dependsOn: ["geo_mentions"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "high" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_answer_position",
    name: "AI Answer Position",
    description: "Average ordinal rank of the brand within AI answers, where 1 means named first.",
    category: "geo",
    source: "Reuses geo_mentions probe responses",
    costPerCallUsd: 0,
    costNote: "Aggregates the same-day geo_mentions snapshot",
    groupedWith: ["geo_mentions"],
    dependsOn: ["geo_mentions"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "high" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_citation_taxonomy",
    name: "Citation Source Taxonomy",
    description: "Classifies AI-cited domains into owned, competitor, press, social, docs, earned and other.",
    category: "geo",
    source: "Reuses geo_citations probe (domain classification)",
    costPerCallUsd: 0,
    costNote: "Aggregates the same-day geo_citations snapshot",
    groupedWith: ["geo_citations"],
    dependsOn: ["geo_citations"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "medium" as ImportanceToRevenue,
  },
  {
    capabilityKey: "geo_ai_search_volume",
    name: "AI Search Volume",
    description: "Estimated monthly AI-assistant query volume for the brand's tracked keywords.",
    category: "geo",
    source: "DataForSEO ai_optimization/ai_keyword_data/keywords_search_volume",
    costPerCallUsd: 0.0101,
    costNote: "measured live — flat ~$0.01 per request plus ~$0.0001 per keyword, batched into one call",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: false,
    importanceToRevenue: "medium" as ImportanceToRevenue,
  },
  {
    capabilityKey: "mentions_brand",
    name: "Brand Mentions",
    description: "Cross-platform brand-name mentions: Twitter, Reddit, HackerNews, YouTube (30-day rolling).",
    category: "mentions",
    source: "Twitter API v2 + Reddit API + HN Algolia + YouTube Data API",
    costPerCallUsd: 0,
    costNote: "All free-tier APIs",
    groupedWith: ["mentions_keyword"],
    dependsOn: ["mentions_keyword"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "mentions_keyword",
    name: "Keyword Mentions",
    description: "Cross-platform mentions of tracked keywords across the same surfaces as mentions_brand.",
    category: "mentions",
    source: "Twitter API v2 + Reddit API + HN Algolia + YouTube Data API",
    costPerCallUsd: 0,
    costNote: "All free-tier APIs",
    groupedWith: ["mentions_brand"],
    dependsOn: ["mentions_brand"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "brand_lookalike_domains",
    name: "Lookalike Domains",
    description: "Generates typo/homoglyph/TLD permutations of the brand domain (dnstwist algorithm) and resolves which are registered; enriches live hits with registration date (RDAP) and MX presence to flag email-capable squats.",
    category: "mentions",
    source: "Node DNS + RDAP (dnstwist permutations)",
    costPerCallUsd: 0,
    costNote: "Free — DNS resolution + RDAP lookups",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "brand_phishing",
    name: "Phishing Detection",
    description: "Detects active phishing pages impersonating the brand by matching lookalike domains against the OpenPhish feed and scraping live lookalikes for cloned login forms + brand assets.",
    category: "mentions",
    source: "OpenPhish feed (free) + Firecrawl /v1/scrape",
    costPerCallUsd: 0.015,
    costNote: "Free feed; ~1 Firecrawl credit per scanned lookalike",
    groupedWith: ["brand_lookalike_domains"],
    dependsOn: ["brand_lookalike_domains"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "brand_trademark_abuse",
    name: "Trademark Abuse",
    description: "Classifies each registered lookalike domain's content via LLM as impersonator / unauthorized reseller / parked / unrelated / legitimate to surface trademark misuse.",
    category: "mentions",
    source: "Firecrawl /v1/scrape + OpenRouter (gpt-4o-mini)",
    costPerCallUsd: 0.02,
    costNote: "~1 Firecrawl credit per lookalike + one classification call",
    groupedWith: ["brand_lookalike_domains"],
    dependsOn: ["brand_lookalike_domains"],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "social_youtube_mentions",
    name: "YouTube Brand Mentions",
    description: "Volume + sentiment of YouTube videos discussing the brand (30-day rolling).",
    category: "mentions",
    source: "YouTube Data API search + videos endpoint + OpenRouter (Haiku classify)",
    costPerCallUsd: 0.005,
    costNote: "Free YouTube API + small Haiku classification",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "pr_news_coverage",
    name: "News & Media Coverage",
    description: "News articles mentioning the brand from Google News SERP (30-day rolling).",
    category: "mentions",
    source: "DataForSEO /v3/serp/google/news + OpenRouter (Sonnet sentiment)",
    costPerCallUsd: 0.02,
    costNote: "1 DataForSEO news task + small LLM sentiment pass",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_backlink_changes",
    name: "Backlink Gains / Losses",
    description: "New high-DR backlinks, lost links, toxic links (disavow candidates), and competitor backlink gains (outreach targets).",
    category: "seo",
    source: "DataForSEO Backlinks API (summary + new_lost)",
    costPerCallUsd: 0.04,
    costNote: "Plan-gated — requires DataForSEO Backlinks subscription; off by default",
    groupedWith: [],
    dependsOn: [],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_cannibalization",
    name: "Keyword Cannibalization",
    description: "Finds keywords where two or more of the org's own URLs rank in the same Google SERP, splitting clicks and authority.",
    category: "seo",
    source: "DataForSEO Labs (ranked_keywords) + SERP API (top 20 keywords)",
    costPerCallUsd: 0.02,
    costNote: "~20 SERP probes per run (cached)",
    groupedWith: ["seo_rank"],
    dependsOn: ["seo_rank"],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_indexation_health",
    name: "Indexation Health",
    description: "Composite 0–100 indexation-health score rolling up index coverage, noindex, canonical drift, and sitemap churn.",
    category: "seo",
    source: "DB composite over seo_index_coverage / seo_noindex_alert / seo_canonical_drift / seo_sitemap_diff",
    costPerCallUsd: 0,
    costNote: "Pure DB composite — no external calls",
    groupedWith: ["seo_index_coverage", "seo_noindex_alert", "seo_canonical_drift", "seo_sitemap_diff"],
    dependsOn: ["seo_index_coverage", "seo_noindex_alert", "seo_canonical_drift", "seo_sitemap_diff"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_authority_score",
    name: "Authority Score",
    description: "Domain authority 0–100 (= Semrush Authority Score / Ahrefs Domain Rating), derived by rescaling the DataForSEO domain rank already fetched by seo_backlinks.",
    category: "seo",
    source: "DB composite over seo_backlinks (DataForSEO domain rank)",
    costPerCallUsd: 0,
    costNote: "Pure DB composite — no external calls",
    groupedWith: ["seo_backlinks"],
    dependsOn: ["seo_backlinks"],
    runFrequency: "weekly" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_site_health",
    name: "Site Health",
    description: "Composite 0–100 technical-health score rolling up the technical SEO signals by severity (errors / warnings / notices), with fixed-vs-new deltas.",
    category: "seo",
    source: "DB composite over seo_error_spike / seo_canonical_drift / seo_noindex_alert / seo_cwv / seo_internal_linking / seo_indexation_health",
    costPerCallUsd: 0,
    costNote: "Pure DB composite — no external calls",
    groupedWith: ["seo_error_spike", "seo_canonical_drift", "seo_noindex_alert", "seo_cwv", "seo_internal_linking", "seo_indexation_health"],
    dependsOn: ["seo_error_spike", "seo_canonical_drift", "seo_noindex_alert", "seo_cwv", "seo_internal_linking", "seo_indexation_health"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_position_distribution",
    name: "Position Distribution",
    description: "Keyword counts across the 1–3 / 4–10 / 11–20 / 21–50 / 51–100 ranking buckets, derived from the ranked keywords seo_keyword_changes already fetches.",
    category: "seo",
    source: "DB composite over seo_keyword_changes (DataForSEO ranked keywords)",
    costPerCallUsd: 0,
    costNote: "Pure DB composite — no external calls",
    groupedWith: ["seo_keyword_changes"],
    dependsOn: ["seo_keyword_changes"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_traffic_value",
    name: "Traffic Value",
    description: "Estimated dollar value of organic traffic: organic CTR-by-position × search volume × CPC, i.e. what the traffic would cost via paid search.",
    category: "seo",
    source: "DB composite over seo_keyword_changes (DataForSEO ranked keywords)",
    costPerCallUsd: 0,
    costNote: "Pure DB composite — no external calls",
    groupedWith: ["seo_keyword_changes"],
    dependsOn: ["seo_keyword_changes"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
  {
    capabilityKey: "seo_serp_volatility",
    name: "SERP Volatility",
    description: "Day-over-day flux across tracked keyword positions (= Semrush Sensor). High shared movement flags a likely Google algorithm update vs a site-specific issue.",
    category: "seo",
    source: "DB composite over consecutive seo_keyword_changes snapshots",
    costPerCallUsd: 0,
    costNote: "Pure DB composite — no external calls",
    groupedWith: ["seo_keyword_changes"],
    dependsOn: ["seo_keyword_changes"],
    runFrequency: "daily" as RunFrequency,
    cached: true,
    importanceToRevenue: "unknown" as ImportanceToRevenue,
  },
];

/** Upstream lineage edges: capability → direct producer keys (from catalog dependsOn). */
export const SIGNAL_LINEAGE: Readonly<Record<CapabilityKey, readonly CapabilityKey[]>> = {
  brand_lookalike_domains: [],
  brand_phishing: ["brand_lookalike_domains"],
  brand_trademark_abuse: ["brand_lookalike_domains"],
  geo_accuracy_audit: [],
  geo_ai_search_volume: [],
  geo_alternatives: [],
  geo_answer_position: ["geo_mentions"],
  geo_citation_authority: ["geo_citations"],
  geo_citation_sources: ["geo_citations"],
  geo_citation_taxonomy: ["geo_citations"],
  geo_citation_velocity: ["geo_citations"],
  geo_citation_why: ["geo_citations"],
  geo_citations: [],
  geo_co_citations: ["geo_citations"],
  geo_competitor_visibility: [],
  geo_content_gap: [],
  geo_engine_citations: [],
  geo_keyword_citations: ["geo_citations"],
  geo_mentions: ["geo_citations"],
  geo_mentions_geo: [],
  geo_prompt_research: [],
  geo_sentiment: ["geo_mentions"],
  geo_shopping_citation: [],
  geo_social_signals: [],
  geo_traffic_estimate: ["geo_citations"],
  geo_traffic_lift: ["geo_traffic_estimate", "geo_competitor_visibility", "geo_content_gap"],
  geo_visibility_score: ["geo_citations", "geo_mentions"],
  geo_youtube_citations: [],
  mentions_brand: ["mentions_keyword"],
  mentions_keyword: ["mentions_brand"],
  pr_news_coverage: [],
  seo_answer_box: ["seo_rank"],
  seo_authority_score: ["seo_backlinks"],
  seo_backlink_changes: [],
  seo_backlinks: [],
  seo_cannibalization: ["seo_rank"],
  seo_canonical_drift: ["seo_noindex_alert"],
  seo_competitor_pages: [],
  seo_content_decay: [],
  seo_content_freshness: [],
  seo_content_score: [],
  seo_ctr_anomaly: ["seo_content_decay"],
  seo_cwv: [],
  seo_error_spike: ["seo_sitemap_diff"],
  seo_index_coverage: ["seo_noindex_alert"],
  seo_indexation_health: ["seo_index_coverage", "seo_noindex_alert", "seo_canonical_drift", "seo_sitemap_diff"],
  seo_internal_linking: [],
  seo_international_rank: [],
  seo_keyword_changes: ["seo_rank"],
  seo_keyword_gap: [],
  seo_keyword_intent: [],
  seo_local_rank: [],
  seo_noindex_alert: ["seo_canonical_drift"],
  seo_position_distribution: ["seo_keyword_changes"],
  seo_rank: [],
  seo_serp_features: ["seo_rank"],
  seo_serp_volatility: ["seo_keyword_changes"],
  seo_site_health: ["seo_error_spike", "seo_canonical_drift", "seo_noindex_alert", "seo_cwv", "seo_internal_linking", "seo_indexation_health"],
  seo_sitemap_diff: [],
  seo_sov: ["seo_rank"],
  seo_top_pages: [],
  seo_traffic_trend: [],
  seo_traffic_value: ["seo_keyword_changes"],
  social_youtube_mentions: [],
} as const;
