import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const configPath = "./src/lib/auth.ts";
const outputPath = "./src/server/db/models/auth.model.ts";

console.log("Generating Better Auth schema...");

try {
  execSync(
    `bunx @better-auth/cli generate --config ${configPath} --output ${outputPath} --yes`,
    { stdio: "inherit", env: { ...process.env, SKIP_ENV_VALIDATION: "true" } },
  );

  const disclaimer = `// =================================================================================================
//
// THIS FILE IS AUTOGENERATED BY THE BETTER-AUTH CLI
//
// DO NOT EDIT THIS FILE MANUALLY
//
// RUN 'bun run auth:generate' TO REGENERATE
//
// =================================================================================================

`;
  const schemaContent = readFileSync(outputPath, "utf-8");
  writeFileSync(outputPath, disclaimer + schemaContent);
  console.log("Done!");
} catch (error) {
  console.error("Failed to generate schema:", error);
  process.exit(1);
}
